import { Toast } from "bootstrap";
import { writable } from "svelte/store";

export const admin_logged_in_state = writable(false);
export const user_logged_in_state = writable(false);
export const username_state = writable("");
export const current_level_state = writable(-1);
export const current_rank_state = writable(-1);
export const next_level_id_state = writable<number | null>(null);
export const next_level_url_state = writable("");
export const correct_answer_toast_store = writable(new Toast(""));
export const wrong_answer_toast_store = writable(new Toast(""));
export const success_toast_store = writable(new Toast(""));
export const fail_toast_store = writable(new Toast(""));
export const server_error_toast_store = writable(new Toast(""));
export const unverified_toast_store = writable(new Toast(""));
export const unauthorized_toast_store = writable(new Toast(""));
export const user_not_found_toast_store = writable(new Toast(""));
export const password_unmatched_toast_store = writable(new Toast(""));
export const banned_toast_store = writable(new Toast(""));
export const student_id_misformation_toast_store = writable(new Toast(""));
export const roll_out_of_range_toast_store = writable(new Toast(""));
export const improper_username_toast_store = writable(new Toast(""));
export const invalid_email_toast_store = writable(new Toast(""));
export const duplicate_username_student_id_toast_store = writable(
  new Toast("")
);
export const duplicate_puzzle_level_store = writable(new Toast(""));
export const asked_too_many_otp_toast_store = writable(new Toast(""));
export const otp_mismatch_toast_store = writable(new Toast(""));
export const Invalid_otp_user_toast_store = writable(new Toast(""));
export const otp_time_limit_over_toast_store = writable(new Toast(""));
export const otp_user_id_mail_exists_toast_store = writable(new Toast(""));
export const otp_username_exists_toast_store = writable(new Toast(""));
export const otp_student_id_exists_toast_store = writable(new Toast(""));
export const otp_mail_exists_toast_store = writable(new Toast(""));
export const otp_user_nonexistent_toast_store = writable(new Toast(""));
export const otp_user_already_verified_toast_store = writable(new Toast(""));
export const otp_sent_toast_store = writable(new Toast(""));
export const email_not_found_toast_store = writable(new Toast(""));
export const email_send_failed_toast_store = writable(new Toast(""));
export const too_many_otp_mismatch_toast_store = writable(new Toast(""));
