apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-pp
  namespace: website
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/limit-rps: "100"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
spec:
  tls:
    - hosts:
        - puzzle.buetcsefest2024.com
      secretName: letsencrypt-puzzle
  rules:
    - host: puzzle.buetcsefest2024.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pp
                port:
                  number: 80
  ingressClassName: nginx
